

[workspace]
resolver = "2"
members = ["loreal_cli","loreal_lexer"]




[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Pasindu Pramodya"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/loreal-lang/loreal"
